# YAML NOTE: Indentation, spacing and text case are super important.
# This file must be encoded as Unicode (UTF-8) for it to work properly.

# You can change your color palette in the theme options.yml file.
# Change your icon set to 24bit alpha if using dark background. 
# Change icons in theme options.yml file.

# RECOMMENDATION: This color palette works well with 1bit icons also. 

### Main colors
### These colors affect elements listed in optional colors if not activated

back:                   '#0a0a0a'
main_link:              '#A8A8A8'
main_link_hover:        '#4da6f0'
main_link_back_hover:   '#1a1a1a'
line:                   '#2a2a2a'
text_strong:            '#D0D0D0'
text:                   '#8A8A8A'
text_light:             '#A8A8A8'
text_dimmed:            '#606060'
flash:                  'red'

### Optional colors
### Remove "#" to activate optional color and override defaults

# border:               'transparent'
# gallery_link:         '#000000'
gallery_link_hover:     '#D0D0D0'
gallery_back:           '#111'
gallery_back_hover:     '#1c7ad5'
# feature_link:         '#000000'
# feature_link_hover:   '#000000'
feature_text_hover:     '#A0A0A0'
# feature_back:         '0000000'
# feature_back_hover:   '#000000'
sub_link:               '#A8A8A8'
sub_link_hover:         '#bbb'
# sub_link_back_hover:  '#000000'
back_shift:             '#111'
