/**
 * Pre-build CSS generation — runs BEFORE `astro build`/`astro dev` (see package.json),
 * alongside gen-thumbs.mjs.
 *
 * Why a separate pass: the served CSS (public/css/main.css + icons.css) is compiled
 * from the SCSS in src/styles/, but both entrypoints `@import '../img/icons'` — a
 * Sass map of SVG data-URIs that the *upstream grunt pipeline* generated (the `svgcss`
 * task) and never checked in. Without it, `sass src/styles/main.scss` fails with
 * "Can't find stylesheet to import". So this script reproduces that step: it builds
 * src/img/_icons.scss from the vendored SVG sources, then compiles both entrypoints
 * with dart-sass and adds vendor prefixes via lightningcss (mirroring upstream's
 * autoprefixer postcss step). Goal is VISUAL parity with the old hand-committed CSS,
 * not byte-for-byte reproduction.
 *
 * Generated artifacts (gitignored): src/img/_icons.scss, public/css/main.css,
 * public/css/icons.css. The SVG sources in src/img/svg_source/ ARE committed (real
 * source). Layout.astro's <link href="/css/main.css"> is unchanged — we write to those
 * exact paths.
 *
 * Mirrors ../subfolio/config/themes/default/grunt/{svgcss,sass,postcss}.js.
 */
import * as sass from "sass";
import { transform } from "lightningcss";
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join, basename } from "node:path";

const root = resolve(import.meta.dirname, "..");
const svgSourceDir = join(root, "src/img/svg_source");
const iconsPartial = join(root, "src/img/_icons.scss");
const stylesDir = join(root, "src/styles");
const outDir = join(root, "public/css");

// Upstream svgcss defaults (grunt/svgcss.js): defaultWidth/Height = 16px.
const DEFAULT_DIM = 16;

// Vendor-prefix targets mirroring upstream autoprefixer's "last 5 versions"
// (grunt/postcss.js). Encoded as lightningcss browser-version ints (major << 16).
// Deliberately old floors so legacy prefixes (-webkit-/-moz-/-ms-) are emitted.
const targets = {
  chrome: 49 << 16,
  firefox: 45 << 16,
  safari: (9 << 16) | (1 << 8),
  ie: 11 << 16,
  edge: 15 << 16,
};

/**
 * Minify an SVG body for data-URI embedding the way SVGO/grunt-svg-css did: drop the
 * XML prolog, comments, and DOCTYPE, then collapse inter-tag whitespace. We keep the
 * markup otherwise intact (no path re-encoding) — it renders identically.
 */
function cleanSvg(raw) {
  return raw
    .replace(/<\?xml[\s\S]*?\?>/gi, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/<!DOCTYPE[\s\S]*?>/gi, "")
    .replace(/\s*\n\s*/g, " ")
    .replace(/>\s+</g, "><")
    .trim();
}

/** Parse a `width="20px"`/`height="14px"` attribute off the <svg> tag. */
function dimOf(svg, attr) {
  const m = svg.match(new RegExp(`<svg[^>]*\\b${attr}\\s*=\\s*"([0-9.]+)`, "i"));
  return m ? Math.round(parseFloat(m[1])) : DEFAULT_DIM;
}

/** Build the $icons Sass map partial from every SVG in svg_source/. */
function generateIconsPartial() {
  const files = readdirSync(svgSourceDir)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  const entries = files.map((file) => {
    const name = basename(file, ".svg");
    const raw = readFileSync(join(svgSourceDir, file), "utf8");
    const cleaned = cleanSvg(raw);
    const width = dimOf(cleaned, "width");
    const height = dimOf(cleaned, "height");
    // Match the upstream data-URI shape: charset=US-ASCII + URL-encoded markup.
    const datauri = `data:image/svg+xml;charset=US-ASCII,${encodeURIComponent(cleaned)}`;
    return `  ${name}: ( datauri:'${datauri}', width:${width}px, height:${height}px ),`;
  });

  const out =
    `/*!\n * Generated by scripts/gen-css.mjs — DON'T EDIT THIS FILE\n */\n` +
    `$icons: (\n${entries.join("\n")}\n);\n`;

  mkdirSync(join(root, "src/img"), { recursive: true });
  writeFileSync(iconsPartial, out);
  return files.length;
}

/** Compile one SCSS entrypoint → prefixed CSS at public/css/<name>.css. */
function compile(entry) {
  const result = sass.compile(join(stylesDir, entry), {
    loadPaths: [stylesDir],
    silenceDeprecations: ["import", "global-builtin", "color-functions", "slash-div"],
    quietDeps: true,
  });
  const name = basename(entry, ".scss");
  const { code } = transform({
    filename: `${name}.css`,
    code: Buffer.from(result.css),
    targets,
  });
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, `${name}.css`), code);
  return code.length;
}

function main() {
  const iconCount = generateIconsPartial();
  const mainBytes = compile("main.scss");
  const iconsBytes = compile("icons.scss");
  console.log(
    `[gen-css] ${iconCount} icon(s) → _icons.scss; ` +
      `main.css ${(mainBytes / 1024).toFixed(1)}KB, icons.css ${(iconsBytes / 1024).toFixed(1)}KB`,
  );
}

main();
