/**
 * Pre-build CSS generation — runs BEFORE `astro build`/`astro dev` (see package.json),
 * alongside gen-thumbs.mjs.
 *
 * Why a separate pass: the served CSS (public/css/main.css + icons.css) is compiled
 * from the SCSS in src/styles/, but both entrypoints `@import '../img/icons'` — a
 * Sass map of SVG data-URIs that the *upstream grunt pipeline* generated (the `svgcss`
 * task) and never checked in. Without it, `sass src/styles/main.scss` fails with
 * "Can't find stylesheet to import". So this script reproduces that step: it builds
 * src/img/_icons.scss from the vendored SVG sources, then compiles both entrypoints
 * with dart-sass and adds vendor prefixes (mirroring upstream's autoprefixer step).
 *
 * Modernized pipeline (was: grunt svgcss + hand-encoded autoprefixer "last 5 versions"):
 *   - SVGs are optimized with SVGO (drops Illustrator cruft, shortens paths) and
 *     embedded with mini-svg-data-uri's minimal escaping — far smaller than the old
 *     `charset=US-ASCII` + full encodeURIComponent() form, pixel-identical rendering.
 *   - Vendor prefixing targets come from a single `browserslist` query (package.json
 *     "browserslist": ["defaults"]) via lightningcss's browserslistToTargets() — no
 *     more hand-encoded version ints, and IE/dead-browser prefixes are gone.
 *
 * Generated artifacts (gitignored): src/img/_icons.scss, public/css/main.css,
 * public/css/icons.css. The SVG sources in src/img/svg_source/ ARE committed (real
 * source). Layout.astro's <link href="/css/main.css"> is unchanged — we write to those
 * exact paths.
 */
import * as sass from "sass";
import { transform, browserslistToTargets } from "lightningcss";
import browserslist from "browserslist";
import { optimize as svgo } from "svgo";
import svgToTinyDataUri from "mini-svg-data-uri";
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, join, basename } from "node:path";

const root = resolve(import.meta.dirname, "..");
const svgSourceDir = join(root, "src/img/svg_source");
const iconsPartial = join(root, "src/img/_icons.scss");
const stylesDir = join(root, "src/styles");
const outDir = join(root, "public/css");

// Upstream svgcss defaults (grunt/svgcss.js): defaultWidth/Height = 16px.
const DEFAULT_DIM = 16;

// Vendor-prefix targets from the package.json `browserslist` query. One source of
// truth, also discoverable by any other browserslist-aware tooling.
const targets = browserslistToTargets(browserslist());

/**
 * Parse a `width="20px"`/`height="14px"` attribute off the <svg> tag. Run against the
 * RAW source before SVGO so icon sizing is robust even if optimization ever drops the
 * dimension attributes (SVGO's preset-default keeps them today, but don't depend on it).
 */
function dimOf(svg, attr) {
  const m = svg.match(new RegExp(`<svg[^>]*\\b${attr}\\s*=\\s*"([0-9.]+)`, "i"));
  return m ? Math.round(parseFloat(m[1])) : DEFAULT_DIM;
}

/** Build the $icons Sass map partial from every SVG in svg_source/. */
function generateIconsPartial() {
  const files = readdirSync(svgSourceDir)
    .filter((f) => f.endsWith(".svg"))
    .sort();

  const entries = files.map((file) => {
    const name = basename(file, ".svg");
    const raw = readFileSync(join(svgSourceDir, file), "utf8");
    // Dimensions come from the raw markup, before SVGO touches the <svg> tag.
    const width = dimOf(raw, "width");
    const height = dimOf(raw, "height");
    // SVGO strips the XML prolog, DOCTYPE, generator comments, Illustrator ids, and
    // collapses path precision. mini-svg-data-uri then emits the minimally-escaped
    // `data:image/svg+xml,...` form (" → ', only reserved chars percent-encoded).
    const { data: optimized } = svgo(raw, { multipass: true, plugins: ["preset-default"] });
    // mini-svg-data-uri uses single quotes for SVG attrs (smaller than %22), so the
    // Sass string MUST be double-quoted to avoid a quote collision.
    const datauri = svgToTinyDataUri(optimized);
    return `  ${name}: ( datauri:"${datauri}", width:${width}px, height:${height}px ),`;
  });

  const out =
    `/*!\n * Generated by scripts/gen-css.mjs — DON'T EDIT THIS FILE\n */\n` +
    `$icons: (\n${entries.join("\n")}\n);\n`;

  mkdirSync(join(root, "src/img"), { recursive: true });
  writeFileSync(iconsPartial, out);
  return files.length;
}

/** Compile one SCSS entrypoint → prefixed CSS at public/css/<name>.css. */
function compile(entry) {
  const result = sass.compile(join(stylesDir, entry), {
    loadPaths: [stylesDir],
    silenceDeprecations: ["import", "global-builtin", "color-functions", "slash-div"],
    quietDeps: true,
  });
  const name = basename(entry, ".scss");
  const { code } = transform({
    filename: `${name}.css`,
    code: Buffer.from(result.css),
    targets,
  });
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, `${name}.css`), code);
  return code.length;
}

function main() {
  const iconCount = generateIconsPartial();
  const mainBytes = compile("main.scss");
  const iconsBytes = compile("icons.scss");
  console.log(
    `[gen-css] ${iconCount} icon(s) → _icons.scss; ` +
      `main.css ${(mainBytes / 1024).toFixed(1)}KB, icons.css ${(iconsBytes / 1024).toFixed(1)}KB`,
  );
}

main();
